'use client'
import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { useState } from 'react'
import Head from 'next/head'
import { Toaster } from "@/components/ui/toaster"

const jakarta_sans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Test Authentication',
  description: 'Generated by create next app',
}
interface Props{
  children: React.ReactNode;
  session: any
}

export default function RootLayout({children,session}:Props) {
  const [dark, setDark] = useState(true)
  return (
    <html lang="en">
      <Head>
        <meta http-equiv="Permissions-Policy" content="interest-cohort=()"></meta>
      </Head>
      <body className={`${dark && 'dark'} ${jakarta_sans.className}`}>
        <SessionProvider session={session}>
          {/* <button onClick={()=>setDark(!dark)}>Click biar light mode</button> */}
          {children}
        </SessionProvider>
        <Toaster/>
      </body>
      </html>
  )
}
