'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { useState } from 'react'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test Authentication',
  description: 'Generated by create next app',
}
interface Props{
  children: React.ReactNode;
  session: any
}

export default function RootLayout({children,session}:Props) {
  const [dark, setDark] = useState(true)
  return (
    <html lang="en">
      <Head>
        <meta http-equiv="Permissions-Policy" content="interest-cohort=()"></meta>
      </Head>
      <body className={`${dark && 'dark'} ${inter.className }`}>
        <SessionProvider session={session}>
          <button onClick={()=>setDark(!dark)}>Click biar light mode</button>
          {children}
        </SessionProvider>
      </body>
      </html>
  )
}
